collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

category_list: [ jekyll, js, clojure, algo, DB, CS, etc, configs, living ]

plugins:
  - jekyll-feed
  - jekyll-paginate

# paginate_path: /page:num
paginate: 2
paginate_path: "/index/page:num/"

# personal info
title: zerozoo
email: zerozoo385@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  😽
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nil
github_username:  zerozoo-a

algolia:
  index_name: SO3HY1LT1Y
  application_id: 'SO3HY1LT1Y'

sass:
  sass_dir: assets/css

